In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
data = pd.read_csv('DataProcessing.csv')

In [60]:
X = data.iloc[:,:-1].values
Y = data.iloc[:,-1].values

In [61]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Missing Data

In [49]:
from sklearn.impute import SimpleImputer

inputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [62]:
inputer.fit(X[:,1:3])

SimpleImputer()

In [63]:
X[:,1:3] = inputer.transform(X[:,1:3])

In [64]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Encoding data

In [67]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('enconder', OneHotEncoder(), [0])], remainder='passthrough')

In [71]:
X = ct.fit_transform(X)
X

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [72]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [81]:
Y = le.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [78]:
X[0,:]

array([0.0, 1.0, 0.0, 0.0, 44.0, 72000.0], dtype=object)

## Splliting data in Train and Test

In [128]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,Y,train_size=0.8, random_state=1)

In [91]:
X_train,X_test

(array([[1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
        [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
        [0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
        [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
        [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
        [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
        [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object),
 array([[1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
        [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object))

In [92]:
y_train,y_test

(array([0, 1, 0, 0, 1, 1, 0, 1]), array([0, 1]))

## Feature Scaling

In [129]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train[:,4:])

StandardScaler()

In [130]:
X_test[:,4:],X_train[:,4:]


(array([[30.0, 54000.0],
        [37.0, 67000.0]], dtype=object),
 array([[38.77777777777778, 52000.0],
        [40.0, 63777.77777777778],
        [44.0, 72000.0],
        [38.0, 61000.0],
        [27.0, 48000.0],
        [48.0, 79000.0],
        [50.0, 83000.0],
        [35.0, 58000.0]], dtype=object))

In [134]:
X_test[:,4:] = sc.transform(X_test[:,4:])
X_train[:,4:] = sc.transform(X_train[:,4:])

In [135]:
X_train,X_test

(array([[1.0, 0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
        [1.0, 0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
        [0.0, 1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
        [1.0, 0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
        [1.0, 0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
        [0.0, 1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
        [1.0, 0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
        [0.0, 1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
       dtype=object),
 array([[1.0, 0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
        [0.0, 1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
       dtype=object))